<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="16.970" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2024-04-22T06:39:45" tests="0" file="cypress/integration/secondTest.spec.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2024-04-22T06:39:45" tests="1" time="16.962" failures="1">
    <testcase name="Test log out verify use can log out successfully" time="5.334" classname="verify use can log out successfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (webpack://angular-realworld/./cypress/integration/secondTest.spec.js:11:30)]]></failure>
    </testcase>
  </testsuite>
</testsuites>